# Generated by Django 3.0 on 2022-01-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
