# Generated by Django 3.0 on 2022-01-31 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
