# Generated by Django 3.0 on 2022-02-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0012_auto_20220212_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
