from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('contact/',views.contact,name='contact'),
    path('about/',views.about,name='about'),
    path('under-construction/',views.underconstruction,name='under-construction'),
    path('signup/',views.signup,name='signup'),
    path('signin/',views.signin,name='signin'),
    path('logout/',views.logout,name='logout'),
    path('changepassword/',views.changepassword,name='changepassword'),
    path('forgotpassword/',views.forgotpassword, name='forgotpassword'),
    path('otppage/',views.otppage,name='otppage'),
    path('newpasseord/',views.newpassword,name='newpassword'),
    path('sellerindex/',views.sellerindex,name='sellerindex'),
    path('sellerchangepassword/',views.sellerchangepassword,name='sellerchangepassword'),
    path('selleraddproducts/',views.selleraddproducts,name='selleraddproducts'),
    path('sellerviewproducts/',views.sellerviewproducts,name='sellerviewproducts'),
    path('sellereditproducts/<int:pk>/',views.sellereditproducts, name='sellereditproducts'),
    path('sellerdeleteproducts/<int:pk>/',views.sellerdeleteproducts,name='sellerdeleteproducts'),
    path('product_filter/<str:pc>/',views.product_filter,name='product_filter'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('product_detail/<int:pk>/',views.product_detail,name='product_detail'),
    path('add_to_wishlist/<int:pk>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:pk>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('shop/',views.shop,name='shop'),
    path('cart/',views.cart,name='cart'),
    path('add_to_cart/<int:pk>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:pk>/',views.remove_from_cart,name='remove_from_cart'),
    path('checkout/',views.checkout,name='checkout'),
    path('pay/', views.initiate_payment, name='pay'),
    path('callback/', views.callback, name='callback'),
    path('orders/',views.orders,name='orders'),
    path('cancel_order/<int:pk>/',views.cancel_order,name='cancel_order'),   
    path('user_product_filter/<str:pc>/',views.user_product_filter,name='user_product_filter')  ,
    path('ajax/validate_email/', views.validate_email, name='validate_email'),
    path('search/',views.search,name='search'),
]